# Generated by Django 6.0.6 on 2026-07-07 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("running", "RUNNING"),
                            ("waiting_human", "WAITING_HUMAN"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("events", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Run",
                "verbose_name_plural": "Workflow Runs",
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="runs_workfl_status_a4fa16_idx",
                    ),
                    models.Index(
                        fields=["workflow", "-created_at"],
                        name="runs_workfl_workflo_4b0048_idx",
                    ),
                ],
            },
        ),
    ]
