# Generated by Django 6.0.6 on 2026-07-07 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                ("version", models.IntegerField(default=1)),
                ("nodes", models.JSONField(default=list)),
                ("edges", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "indexes": [
                    models.Index(
                        fields=["name", "version"], name="workflows_w_name_945e6f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_workflow_version"
                    )
                ],
            },
        ),
    ]
